export const CATEGORY_MAP = [
  {
    key: 1,
    emoji: '🍕',
    name: 'pizza',
    keywords: ['italian', 'pepperoni', 'cheese', 'pasta', 'calzone'],
  },
  {
    key: 2,
    emoji: '🍺',
    name: 'beer',
    keywords: ['brewery', 'pub', 'ale', 'lager', 'bar'],
  },
  {
    key: 3,
    emoji: '🍣',
    name: 'sushi',
    keywords: ['japanese', 'sashimi', 'roll', 'tempura', 'miso'],
  },
  {
    key: 4,
    emoji: '☕️',
    name: 'coffee',
    keywords: ['cafe', 'espresso', 'latte', 'pastry', 'mocha'],
  },
  {
    key: 5,
    emoji: '🍔',
    name: 'burger',
    keywords: ['fries', 'diner', 'cheeseburger', 'shake', 'grill'],
  },
  {
    key: 6,
    emoji: '🌮',
    name: 'mexican',
    keywords: ['taco', 'burrito', 'salsa', 'guacamole', 'enchilada'],
  },
  {
    key: 7,
    emoji: '🍜',
    name: 'ramen',
    keywords: ['noodle', 'broth', 'japanese', 'miso', 'tonkotsu'],
  },
  {
    key: 8,
    emoji: '🥗',
    name: 'salad',
    keywords: ['healthy', 'greens', 'dressing', 'veggie', 'bowl'],
  },
  {
    key: 9,
    emoji: '🍦',
    name: 'dessert',
    keywords: ['cake', 'ice cream', 'pastry', 'sweet', 'cookie'],
  },
  {
    key: 10,
    emoji: '🍷',
    name: 'wine',
    keywords: ['vineyard', 'bar', 'red', 'white', 'tasting'],
  },
  {
    key: 11,
    emoji: '🍲',
    name: 'asian_fusion',
    keywords: ['thai', 'vietnamese', 'korean', 'chinese', 'noodle'],
  },
  {
    key: 12,
    emoji: '🥪',
    name: 'sandwich',
    keywords: ['deli', 'sub', 'bread', 'panini', 'bodega'],
  },
  {
    key: 13,
    emoji: '🍝',
    name: 'italian',
    keywords: ['pasta', 'pizza', 'risotto', 'lasagna', 'gelato'],
  },
  {
    key: 14,
    emoji: '🥩',
    name: 'steak',
    keywords: ['grill', 'beef', 'ribeye', 'sirloin', 'barbecue'],
  },
  {
    key: 15,
    emoji: '🍗',
    name: 'chicken',
    keywords: ['fried', 'grilled', 'wings', 'nuggets', 'roast'],
  },
  {
    key: 16,
    emoji: '🍤',
    name: 'seafood',
    keywords: ['shrimp', 'fish', 'crab', 'lobster', 'oyster'],
  },
  {
    key: 17,
    emoji: '🍛',
    name: 'indian',
    keywords: ['curry', 'naan', 'tandoori', 'biryani', 'samosa'],
  },
  {
    key: 18,
    emoji: '🥘',
    name: 'spanish',
    keywords: ['paella', 'tapas', 'chorizo', 'sangria', 'churros'],
  },
  {
    key: 19,
    emoji: '🍱',
    name: 'japanese',
    keywords: ['sushi', 'ramen', 'tempura', 'teriyaki', 'sake'],
  },
  {
    key: 20,
    emoji: '🥟',
    name: 'chinese',
    keywords: ['dumpling', 'noodle', 'fried rice', 'dim sum', 'sweet and sour'],
  },
  {
    key: 21,
    emoji: '🧆',
    name: 'middle_eastern',
    keywords: ['falafel', 'hummus', 'kebab', 'shawarma', 'baklava'],
  },
  {
    key: 22,
    emoji: '🥐',
    name: 'bakery',
    keywords: ['bread', 'pastry', 'croissant', 'cake', 'muffin'],
  },
  {
    key: 23,
    emoji: '🍨',
    name: 'ice_cream',
    keywords: ['gelato', 'sundae', 'frozen yogurt', 'sorbet', 'cone'],
  },
  {
    key: 24,
    emoji: '🍹',
    name: 'cocktail',
    keywords: ['bar', 'mixology', 'mojito', 'martini', 'margarita'],
  },
  {
    key: 25,
    emoji: '🍽️',
    name: 'place',
    keywords: ['restaurant', 'eatery', 'diner', 'cafe', 'bistro'],
  },
];
